import type { NextPage } from "next";
import Head from "next/head";
import { graphql, useLazyLoadQuery } from "react-relay";

export const Home: NextPage = () => {
  const data = useLazyLoadQuery(
    graphql`
      query HomeTestQuery {
        test
      }
    `,
    {}
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Github Relay</h1>
        <p>{JSON.stringify(data)}</p>
      </main>
      <footer />
    </div>
  );
};
